repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: ^(.+)?migrations/
        args: ["-l", "79"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(.+)?migrations/
        args: [ "--settings-path", "./setup.cfg" ]