version: "3.7"

x-celery-config: &celery-config
  image: faceswap:latest
  restart: always
  env_file:
    - .env
  volumes:
    - ./faceswap:/app/
    - ./outputs/:/app/outputs/
    - ./tmp/.insightface:/root/.insightface
    - ./tmp/.opennsfw2:/root/.opennsfw2
  networks:
    - backend
  depends_on:
    redis:
      condition: service_healthy
  command: celery -A faceswap worker -l INFO

services:
  faceswap:
    restart: always
    volumes:
      - ./outputs/:/app/outputs/
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: cuda
    command: gunicorn faceswap.wsgi -c gunicorn.conf.py

  frontend:
    restart: always
    image: faceswap-frontend:latest
    ports:
      - "127.0.0.1:8002:80"
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}

  celery:
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  celery-2:
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  celery-3:
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]