version: "3.8"


x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s
  retries: 5
  timeout: 10s

networks:
  backend:
    driver: bridge

volumes:
  redis_data:

services:
  faceswap:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: faceswap:latest-dev
    env_file:
      - .env
    volumes:
      - ./faceswap:/app/
      - ./outputs/:/app/outputs/
      - ../tmp/.insightface:/root/.insightface
      - ../tmp/.opennsfw2:/root/.opennsfw2
    ports:
      - "127.0.0.1:8001:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health/" ]
      <<: *healthcheck_defaults
    networks:
      - backend
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7.2.4
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "192.168.80.198:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      <<: *healthcheck_defaults
    networks:
      - backend

  celery-1:
    image: faceswap:latest-dev
    env_file:
      - .env
    volumes:
      - ./faceswap:/app/
      - ./outputs/:/app/outputs/
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A faceswap worker -l DEBUG

  flower:
    image: faceswap:latest-dev
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
    volumes:
        - ./faceswap:/app/
    ports:
      - "5557:5555"
    command: celery -A faceswap flower --port=5555
