version: "3.7"

x-celery-config: &celery-config
  image: faceswap:latest
  network_mode: host
  restart: always
  env_file:
    - .env
  volumes:
    - ./faceswap:/app/
    - /mnt/share/faceswap/outputs/:/app/outputs/
    - ../tmp/.insightface:/root/.insightface
    - ../tmp/.opennsfw2:/root/.opennsfw2

services:
  celery-1:
    restart: on-failure
    command: celery -A faceswap worker --concurrency=${CELERY_WORKERS} -l INFO -n worker-1@${HOSTNAME} -Ofair --prefetch-multiplier=1 --pool processes
    healthcheck:
      test: ["CMD", "nvidia-smi"]
      interval: 5s
      retries: 0
      timeout: 5s
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  celery-2:
    restart: on-failure
    command: celery -A faceswap worker --concurrency=${CELERY_WORKERS} -l INFO -n worker-2@${HOSTNAME} -Ofair --prefetch-multiplier=1 --pool processes
    healthcheck:
      test: ["CMD", "nvidia-smi"]
      interval: 5s
      retries: 0
      timeout: 5s
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  celery-3:
    restart: on-failure
    command: celery -A faceswap worker --concurrency=${CELERY_WORKERS} -l INFO -n worker-3@${HOSTNAME} -Ofair --prefetch-multiplier=1 --pool processes
    healthcheck:
      test: ["CMD", "nvidia-smi"]
      interval: 5s
      retries: 0
      timeout: 5s
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]

  celery-4:
    restart: on-failure
    command: celery -A faceswap worker --concurrency=${CELERY_WORKERS} -l INFO -n worker-4@${HOSTNAME} -Ofair --prefetch-multiplier=1 --pool processes
    healthcheck:
      test: ["CMD", "nvidia-smi"]
      interval: 5s
      retries: 0
      timeout: 5s
    <<: *celery-config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]