# Generated by Django 5.0.1 on 2024-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_video_show"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_info", models.CharField(max_length=250)),
                ("counter", models.IntegerField()),
            ],
        ),
    ]
